TXTFILES = \
	QuickReference-kmk.txt \
	QuickReference-kBuild.txt

define genrule
all: $(name).html
clean::
	kmk_rm -f $(name).html
$(name).html: $(name).txt
	LC_ALL=C rst2html.py --no-generator $$< $$@
$(name).o: $(name).html
.PHONY: $(name).o
endef

$(foreach name, $(basename $(TXTFILES)), $(eval $(genrule)))

