# $Id$

#
# This is an example makefile.
#

TOOL = GCC
PROGRAMS = helloworld hello world
helloworld_SOURCES = hello.c
hello_SOURCES = hello.c
world_SOURCES = hello.c

DEPTH = ../../..
include $(DEPTH)/kBuild/rules.kMk

