# $Id$

PROGRAMS = kDepCCxx
	
kDepCCxx_TOOL.os2    = GCC3OMF
kDepCCxx_LDFLAGS.os2 = -Zhigh-mem -Zstack=1024
kDepCCxx_DEFS        =
kDepCCxx_DEFS.os2    = NO_X11 __UNIXOS2__ OBJSUFFIX=\".obj\"
kDepCCxx_SOURCES     = \
	main.c \
	cppsetup.c \
	ifparser.c \
	include.c \
	parse.c \
	pr.c


DEPTH = ../..
include $(PATH_KBUILD)/rules.kmk

